### ISSUE TITLE
Would you consider adding a few breaking changes?

### ISSUE THREAD

**Issue by FrancessFractal** [gabrieleds/noop4#2]
We're currently using noop3 over at the is-thirteen project, and are considering updating to noop4 because of it's superior algorithm. However, it appears that noop4 only supports major version 1, while we need major version 13 (see https://github.com/jezen/is-thirteen/issues/151).

I see you're using semantic versioning, and I completely understand not wanting to break that and skip ahead to version 13, since that would seriously inconvenience your users. But I was hoping that maybe you could come up with a series of 12 changes that each break backwards compatibility so that you can make it to major version 13. That way your user base will be satisfied that you upheld the integrity of semantic versioning, but we still get to use version 13!

**Comment by gabrieleds** [comment]
I don't understand the technical reasons to move to a major `13.x.x`
